### ISSUE TITLE
[CERTIFICATE]

### ISSUE THREAD

**Issue by devbn3li** [PanXProject/awesome-certificates#18]
Ask us to find free certificates in a specific field that you couldn't find here and we will add it.
ALX Africa software engineering 12 month with back end or front end specialize
https://www.alxafrica.com/

**Comment by panx-team** [comment]
Thanks for adding! If you find an awesome course/certificate you can add them to this list by opening a pull request instead of opening an issue. 

I've checked ALX and it seems they're currently not accepting applicants. We're looking for course that are always free for everyone and not limited in any way. 

Check the guidelines here:
https://github.com/PanXProject/awesome-certificates/blob/main/pull_request_template.md
